[package]
name = "comedilib"
version = "0.1.0"
authors = ["Szymon Mikulicz <szymon.mikulicz@posteo.net>"]
edition = "2018"

[workspace]
members = [
    "comedilib-sys",
]

[dependencies]
comedilib-sys = { path = "comedilib-sys" }
failure = "0"
enum-repr = "0"
libc = "0"
